language: csharp
solution: VTiger.sln

#os: windows
mono:
  - latest
  
#dotnet: 
#  - 1.0.1
#  - 2.0.0-Preview1
#  - latest
dist: trusty
#sudo: required
#mono: none
install:
  - nuget restore VTiger.sln
#  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
script:
#  - xbuild /p:Configuration="Release via CI" /p:Platform="Any CPU" VTiger.sln
#  - mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./VTigerApiUnitTests/bin/VTigerApiUnitTests.dll
  - msbuild /p:Configuration="Release via CI" /p:Platform="Any CPU" VTiger.sln 